export const FilterActionTypes = {
  TOGGLE_FILTERS: "TOGGLE_FILTERS",
  SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
  SET_SELECTED_DIET_TYPE: "SET_SELECTED_DIET_TYPE",
  SET_SELECTED_ORDER: "SET_SELECTED_ORDER",
};
