export const FilterActionTypes = {
    TOGGLE_IS_ACTIVE: 'TOGGLE_IS_ACTIVE',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
    SET_SELECTED_DIET_TYPE: 'SET_SELECTED_DIET_TYPE',
    SET_SELECTED_ORDER: 'SET_SELECTED_ORDER',
}

