export const RecipeActionTypes = {
    FETCH_RECIPES: 'FETCH_RECIPES',
    FETCH_FAVORITE_RECIPES: 'FETCH_FAVORITE_RECIPES',
    SET_RECIPES: 'SET_RECIPES',
    SET_CURRENT_RECIPE: 'SET_CURRENT_RECIPE',
    SET_PERSIST_RECIPE: 'SET_PERSIST_RECIPE',
    SET_IMAGE: 'SET_IMAGE',
}

