export const RecipeActionTypes = {
    FETCH_RECIPES: 'FETCH_RECIPES',
    FETCH_FAVORITE_RECIPES: 'FETCH_FAVORITE_RECIPES',
    FETCH_MY_RECIPES: 'FETCH_MY_RECIPES',
    FETCH_RECIPES_BY_INGREDIENTS: 'FETCH_RECIPES_BY_INGREDIENTS',
    SET_RECIPES: 'SET_RECIPES',
    SET_MY_RECIPES: 'SET_MY_RECIPES',
    SET_FAVORITE_RECIPES: 'SET_FAVORITE_RECIPES',
    SET_CURRENT_RECIPE: 'SET_CURRENT_RECIPE',
    SET_PERSIST_RECIPE: 'SET_PERSIST_RECIPE',
    SET_IMAGE: 'SET_IMAGE',
    SET_BASE64_IMAGE: 'SET_BASE64_IMAGE',
}

