export const UserActionTypes = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_PICTURE: 'GET_PROFILE_PICTURE',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_TOKEN: 'SET_TOKEN',
    LOGOUT: 'LOGOUT',
}

